version: "1.0"

services:
  web-speed-test-server:
    container_name: web-speed-test-server
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
